language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk15

script:
  - chmod 777 ./gradlew
  - ./gradlew build --info

before_install:
  - sudo apt-get install openssh-client
  - openssl aes-256-cbc -K $encrypted_b4f3819162af_key -iv $encrypted_b4f3819162af_iv
    -in travis_key.enc -out ~/travis_key -d

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "./build/libs/vkBot.jar"
  skip_cleanup: true

after_success:
  - echo -e "Host 130.61.203.95\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./travis_key
  - sudo scp ./build/libs/vkBot.jar ubuntu@${SERVER_IP}:/home/ubuntu/test.jar
