language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk15

script:
  - chmod 777 ./gradlew
  - ./gradlew build --info

before_install:
  - sudo apt-get install openssh-client

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "./build/libs/vkBot.jar"
  skip_cleanup: true

after_success:
  - sudo echo "${SSH_KEY}" > ~/.ssh/authorized_keys
  - sudo chmod 400 ~/.ssh/authorized_keys
  - sudo ssh-keyscan ${SERVER_IP} >> ~/.ssh/authorized_keys
  - sudo scp ./build/libs/vkBot.jar ubuntu@${SERVER_IP}:/home/ubuntu/test.jar
