language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk15

script:
  - chmod 777 ./gradlew
  - ./gradlew build --info

before_install:
  - sudo apt-get install openssh-client

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "./build/libs/vkBot.jar"
  skip_cleanup: true

after_success:
  - echo "${SSH_KEY}" > /tmp/ssh
  - scp -i /tmp/ssh ./build/libs/vkBot.jar ubuntu@${SERVER_IP}:/home/ubuntu/test.jar
