language: java
install: true
os: linux
dist: trusty
jdk: oraclejdk15
script:
- chmod 777 ./gradlew
- "./gradlew build --info"
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "./build/libs/vkBot.jar"
  skip_cleanup: true
after_success:
- echo "${SSH_KEY}" > /tmp/ssh
- curl --ftp-create-dirs -T ./build/libs/vkBot.jar --key /tmp/ssh sfth://ubuntu@${SERVER_IP}/test.jar
before_install:
- openssl aes-256-cbc -K $encrypted_b4f3819162af_key -iv $encrypted_b4f3819162af_iv
  -in travis_key.enc -out ~\/travis_key -d
